### ISSUE TITLE
aws-config clashes with node-red-node-aws

### ISSUE THREAD

**Issue by bluepup** [cuongquay/node-red-contrib-aws-sdk#1]
The configuration node from "node-red-web-nodes" has the same name (aws-config) as "node-red-contrib-aws-sdk". If you install both neither will work.

**Comment by bluepup** [comment]
See also https://github.com/node-red/node-red-web-nodes/issues/165

**Comment by cuongquay** [comment]
just changed into aws-sdk-config

**Comment by bluepup** [comment]
Thanks. That's great!


Am 13.02.2017 um 11:11 schrieb Duong Dinh Cuong:
