### ISSUE TITLE
Update for node-red

### ISSUE THREAD

**Issue by softy2k** [cuongquay/node-red-contrib-aws-sdk#10]
Hello
In node-red , **node-red-contrib-aws-sdk** version is **0.1.7** (older, from some years)

I installed version 0.1.8 , but manually.

Can an update be made to make the latest version accessible directly from **Manage pallete** (node-red browser) ?

**Comment by ktalkington** [comment]
Would like to see 0.1.9 update to the pallete at this point

**Comment by softy2k** [comment]
Still 0.1.7 to me.
I will wait... more

**Comment by cuongquay** [comment]
> Still 0.1.7 to me. I will wait... more

Can you make a pull request?

**Comment by cuongquay** [comment]
> > Still 0.1.7 to me. I will wait... more
> 
> Can you make a pull request?

Srry, the publishing script has been failed since the last time you request. It's pushed now to npm with 0.1.10
