### ISSUE TITLE
Uncaught error may crash nodered

### ISSUE THREAD

**Issue by bluepup** [cuongquay/node-red-contrib-aws-sdk#4]
An uncaught error can result in a crash of nodered.
It seems that e.g. the function node from the nodered core nodes prevents this by running code in a kind of "sandbox".
Because the error is not contained by the node-red-contrib-aws-sdk
 node it seems to crash the whole server, interrupting operations of the other nodes.

I unintentionally provoked such a crash by calling
`node.err("foo");` instead of `node.error("foo");`

**Comment by cuongquay** [comment]
What can you propose for a fix? Please create a pull request.
